### ISSUE TITLE
Create JSON out of ingredients

### ISSUE THREAD

**Issue by pampersrocker** [lab132/PyBake#1]
The json metafile (names anyone?) for a crumble needs to be generated out of the ingredients which is generated by the user provided recipe.py using the oven. (It all makes sense does it?)

This json file identifies all tagged components which are used in the crumble and will be used for lookups when downloading files for a specific platform / tag.

**Comment by Manuzor** [comment]
I've basically implemented it already. Just pushed it to `oven`.

I tested it with my local installation of the ezEngine and the recipe.py in samples/serverSideCrumbleDescription.

So far, the json is only printed to stdout because I'm not sure what should happen with it. Do I save it as a file somewhere as "pastry.json" or do I transfer it directly to the server?

**Comment by pampersrocker** [comment]
I think it does make sense to save it as a file, then you can upload it to the server and also use it to check the integrity of the crumble.

**Comment by Manuzor** [comment]
`oven` is merged to `master` now, so we can close this issue for now. I'm sure there will be smaller issues that still need fixing, but basic functionality is there now, which was the goal of this ticket.
